# Development overrides for docker-compose
# This file is automatically loaded by docker-compose

services:
  frontend:
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # For file watching in Docker
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    stdin_open: true  # For React interactive mode
    tty: true

  backend:
    environment:
      - NODE_ENV=development
      - DEBUG=app:*
    volumes:
      - ./backend:/app:cached
      - /app/node_modules
    stdin_open: true
    tty: true

  postgres:
    environment:
      - POSTGRES_DB=vibe_kanban_dev
    ports:
      - "5432:5432"  # Expose for development tools

  redis:
    ports:
      - "6379:6379"  # Expose for development tools

  qdrant:  
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API